openapi: 3.0.1
info:
  title: 영화 검색 API
  description: OMDb API를 사용하여 영화를 검색하는 API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/movie:
    post:
      summary: 영화 검색 또는 영화 세부정보 가져오기
      description: 제목과 페이지, 또는 ID를 기반으로 OMDb API에서 영화 데이터를 가져옵니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              oneOf:
                - description: '제목과 페이지로 영화 검색 요청'
                  properties:
                    title:
                      type: string
                      description: 검색할 영화의 제목 (영문으로만 검색 가능).
                    page:
                      type: integer
                      description: 검색 결과의 페이지 번호.
                  required:
                    - title
                    - page
                - description: 'ID로 특정 영화의 세부정보 요청'
                  properties:
                    id:
                      type: string
                      description: 세부정보를 가져올 영화의 고유 식별자.
                  required:
                    - id
            examples:
              TitleAndPage:
                summary: 영화 검색 하기 ("title"은 영문으로 입력해야 검색이 가능합니다.)
                value:
                  title: inception
                  page: 1
              IdOnly:
                summary: 영화 상세 데이터 조회하기 ("id"는 영화 검색을 했을 때 응답받을 수 있는 값입니다.)
                value:
                  id: tt1375666
      responses:
        '200':
          description: 영화 데이터와 함께 성공적인 응답
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/MovieSearchResponse'
                  - $ref: '#/components/schemas/MovieDetailsResponse'
              examples:
                SearchExample:
                  summary: 영화 검색 하기
                  value:
                    Response: 'True'
                    Search:
                      - Title: 'Inception'
                        Year: '2010'
                        imdbID: 'tt1375666'
                        Type: 'movie'
                        Poster: 'https://example.com/poster.jpg'
                    Error: ''
                DetailExample:
                  summary: 영화 상세 데이터 조회하기
                  value:
                    Response: 'True'
                    Title: 'Inception'
                    Year: '2010'
                    imdbID: 'tt1375666'
                    Type: 'movie'
                    Poster: 'https://example.com/poster.jpg'
                    Released: '2010-07-16'
                    Runtime: '148 min'
                    Country: 'USA'
                    Plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given a final chance at redemption...'
                    Ratings:
                      - Source: 'Internet Movie Database'
                        Value: '8.8/10'
                    Actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page'
                    Director: 'Christopher Nolan'
                    Production: 'Warner Bros.'
                    Genre: 'Action, Adventure, Sci-Fi'
        '400':
          description: 잘못된 입력으로 인한 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: '잘못된 요청'
        '500':
          description: 내부 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: '데이터를 처리하는 동안 오류가 발생했습니다.'
components:
  schemas:
    MovieSearchResponse:
      type: object
      properties:
        Response:
          type: string
          example: 'True'
        Search:
          type: array
          items:
            type: object
            properties:
              Title:
                type: string
                example: 'Inception'
              Year:
                type: string
                example: '2010'
              imdbID:
                type: string
                example: 'tt1375666'
              Type:
                type: string
                example: 'movie'
              Poster:
                type: string
                example: 'https://example.com/poster.jpg'
        Error:
          type: string
          example: ''
    MovieDetailsResponse:
      type: object
      properties:
        Response:
          type: string
          example: 'True'
        Title:
          type: string
          example: 'Inception'
        Year:
          type: string
          example: '2010'
        imdbID:
          type: string
          example: 'tt1375666'
        Type:
          type: string
          example: 'movie'
        Poster:
          type: string
          example: 'https://example.com/poster.jpg'
        Released:
          type: string
          example: '2010-07-16'
        Runtime:
          type: string
          example: '148 min'
        Country:
          type: string
          example: 'USA'
        Plot:
          type: string
          example: 'A thief who steals corporate secrets through the use of dream-sharing technology is given a final chance at redemption...'
        Ratings:
          type: array
          items:
            type: object
            properties:
              Source:
                type: string
                example: 'Internet Movie Database'
              Value:
                type: string
                example: '8.8/10'
        Actors:
          type: string
          example: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page'
        Director:
          type: string
          example: 'Christopher Nolan'
        Production:
          type: string
          example: 'Warner Bros.'
        Genre:
          type: string
          example: 'Action, Adventure, Sci-Fi'
